project:
  type: website
  output-dir: docs

website:
  # --------------------------------------------------------------------------
  # General website settings
  # --------------------------------------------------------------------------
  title: "Connor Robertson"
  # favicon: assets/wavy-dash-svgrepo-com.svg
  favicon: assets/circle-svgrepo-com.svg
  search:
    location: navbar
    type: textbox
  # --------------------------------------------------------------------------
  # Top bar
  # --------------------------------------------------------------------------
  navbar:
    left:
      - text: "Resume"
        file: resume.qmd
      - text: "Research"
        file: research/research.qmd
      - text: "Docs"
        file: other/docs/docs.qmd
      - text: "Other"
        menu:
          - text: "Machine Learning and Optimization Seminar"
            file: other/mlseminar/mlseminar.qmd
          - text: "Teaching (NJIT)"
            file: other/teaching/teaching.qmd
  # --------------------------------------------------------------------------
  # Footer
  # --------------------------------------------------------------------------
  page-footer:
    right: "Connor Robertson, Copyright 2025"
    left:
      - icon: linkedin
        href: https://www.linkedin.com/in/connor-robertson-773ba8b1/
      - icon: github
        href: https://github.com/cnrrobertson
  # --------------------------------------------------------------------------
  # Sidebar
  # --------------------------------------------------------------------------
  sidebar:
    - title: "Teaching"
      style: "floating"
      collapse-level: 1
      contents:
        - other/teaching/teaching.qmd
        - section: "Math 111 - Calculus I"
          href: other/teaching/math111/math111.qmd
          contents:
            - other/teaching/math111/quizzes/quiz1.qmd
            - other/teaching/math111/quizzes/quiz2.qmd
            - other/teaching/math111/quizzes/quiz3.qmd
            - other/teaching/math111/quizzes/quiz4.qmd
            - other/teaching/math111/quizzes/quiz5.qmd
            - other/teaching/math111/quizzes/quiz6.qmd
            - other/teaching/math111/quizzes/quiz7.qmd
            - other/teaching/math111/quizzes/quiz8.qmd
            - other/teaching/math111/quizzes/quiz9.qmd
            - other/teaching/math111/quizzes/quiz10.qmd
        - section: "Math 340 - Applied Numerical Methods"
          contents:
            - other/teaching/math340/Lab1_matlab_taylor_series/Lab1_matlab_intro.qmd
            - other/teaching/math340/Lab2_bisection/Lab2_bisection.qmd
            - other/teaching/math340/Lab3_fixed_point/Lab3_fixed_points.qmd
            - other/teaching/math340/Lab4_secant/Lab4_secant.qmd

# --------------------------------------------------------------------------
# Theme
# --------------------------------------------------------------------------
format:
  html:
    theme:
      light: simplex
      dark: cyborg
    css: styles.css
    toc: true

# --------------------------------------------------------------------------
# Execution global options
# --------------------------------------------------------------------------
execute:
  freeze: auto

# --------------------------------------------------------------------------
# Plugins
# --------------------------------------------------------------------------
filters:
  - shinylive
