project:
  type: website
  output-dir: docs

website:
  # --------------------------------------------------------------------------
  # General website settings
  # --------------------------------------------------------------------------
  title: "Connor Robertson"
  # favicon: assets/wavy-dash-svgrepo-com.svg
  favicon: assets/circle-svgrepo-com.svg
  search:
    location: navbar
    type: textbox
  # --------------------------------------------------------------------------
  # Top bar
  # --------------------------------------------------------------------------
  navbar:
    left:
      - text: "CV"
        href: assets/CV_Connor_Robertson_10_22.pdf
      - text: "Teaching"
        file: teaching/teaching.qmd
      - text: "Research"
        file: research/research.qmd
      - text: "Other"
        menu:
          - text: "Just for Fun"
            file: other/fun/fun.qmd
          - text: "Machine Learning and Optimization Seminar"
            file: other/mlseminar/mlseminar.qmd
  # --------------------------------------------------------------------------
  # Footer
  # --------------------------------------------------------------------------
  page-footer: 
    right: "Connor Robertson, Copyright 2022" 
    left:
      - icon: linkedin
        href: https://www.linkedin.com/in/connor-robertson-773ba8b1/
      - icon: github
        href: https://github.com/cnrrobertson
  # --------------------------------------------------------------------------
  # Sidebar
  # --------------------------------------------------------------------------
  sidebar:
    - title: "Teaching"
      style: "floating"
      collapse-level: 1
      contents:
        - teaching/teaching.qmd
        - section: "Math 111 - Calculus I"
          href: teaching/math111/math111.qmd
          contents:
            - teaching/math111/quizzes/quiz1.qmd
            - teaching/math111/quizzes/quiz2.qmd
            - teaching/math111/quizzes/quiz3.qmd
            - teaching/math111/quizzes/quiz4.qmd
            - teaching/math111/quizzes/quiz5.qmd
        - section: "Math 340 - Applied Numerical Methods"
          contents:
            - teaching/math340/Lab1_matlab_taylor_series/Lab1_matlab_intro.qmd
    - title: "Research"
      style: "floating"
      collapse-level: 1
      contents:
        - section: "Research"
          href: research/research.qmd
          contents:
            - text: "Data-driven modeling of active nematics"
              href: research/active_nematics.qmd
    - title: "Just for Fun"
      style: "floating"
      collapse-level: 1
      contents:
        - section: "Just for fun"
          href: other/fun/fun.qmd
          contents:
            - text: "Polygon angles"
              href: other/fun/polygon_angles.qmd
            - text: "Geocentrism"
              href: other/fun/heliocentric_geocentric.qmd
    - title: "Machine Learning and Optimization Seminar"
      style: "floating"
      collapse-level: 1
      contents:
        - section: "Machine Learning and Optimization Seminar"
          href: other/mlseminar/mlseminar.qmd
          contents:
            - text: "Workshop 1: Python set up, basics, gradient descent, automatic differentiation"
              href: other/mlseminar/fall_2022/workshop1_intro/workshop1_intro.qmd
            - text: "Workshop 2: Neural networks - structure, building, and training"
              href: other/mlseminar/fall_2022/workshop2_nn/workshop2_nn.qmd
            - text: "Workshop 3: Data-driven discovery via Sparse Identification of Nonlinear Dynamics"
              href: other/mlseminar/fall_2022/workshop3_discovery/workshop3_discovery.qmd

# --------------------------------------------------------------------------
# Theme
# --------------------------------------------------------------------------
format:
  html:
    theme: 
      light: simplex
      dark: cyborg
    css: styles.css
    toc: true

# --------------------------------------------------------------------------
# Execution global options
# --------------------------------------------------------------------------
execute:
  freeze: auto

