[project]
name = "cnrrobertson.github.io"
version = "0.1.0"
description = "Add a short description here"
authors = ["Connor Robertson <cnr.robertson@gmail.com>"]
channels = ["conda-forge", "https://repo.prefix.dev/julia-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.0.0,<2.1"
opencv = ">=4.10.0,<4.11"
matplotlib = ">=3.9.0,<3.10"
jupyter = ">=1.0.0,<1.1"
julia = ">=1.10.4,<1.11"
